language: node_js
node_js:
  - "0.12"

addons:
  sauce_connect: true

env:
  global:
    - secure: CdijnSdqo9ullIVPmckWA/BRVRYczDDSDuMyvVXERRiktBAcqqcnHY7/xkPearisnZMU1xPGkQ4Bm1NT66W5pSRKLWmiTDeVZnwJRf2fWlZrN1Vw6yOAIMmZ+F2Ie+Ng09YkSUnotnGOkNbyg+ypMto84GX96cZTVLF0OgYDhgY=
    - secure: aCT4TPwPb/TzruOKp1e5hmY5puqg99DJ+o2XuMFibT6hX29nYVxpWS3HY9D4zjtyaCq0HLk+/ST7vZKgeQbYOc/Wk6l7HC+tyo+euMayvGyOUFrgqp4B1Vr1YGj3bKFAx1i/vMtjfCV5irHgvdrZEC4Wzg+zMo6TDWp6fDYLxm8=
